# 电机电流片选
motor_current_select:
  current1: "11"
  current2: "11"
  current3: "11"
  magnetic_current: "11"

# 电流1设置
current1_settings:
  tail: "0C01"

# 电流2设置
current2_settings:
  tail: "0D01"

# 电流3设置
current3_settings:
  tail: "0E01"

# 磁场电流设置
magnetic_current_settings:
  tail: "F800"